"""make jockey and trainer code nullable use name_cn as key

Revision ID: 38e7c088ce19
Revises: 28cab3607e19
Create Date: 2026-01-08 23:42:25.750728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e7c088ce19'
down_revision: Union[str, Sequence[str], None] = '28cab3607e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jockey', 'code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('jockey', 'name_cn',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('trainer', 'code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('trainer', 'name_cn',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainer', 'name_cn',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('trainer', 'code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('jockey', 'name_cn',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('jockey', 'code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###
