"""Initial schema: 9 tables with relationships

Revision ID: 676929856237
Revises:
Create Date: 2026-01-04 18:53:40.240417

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "676929856237"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "horse_profile_history",
        "captured_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("horse_profile_history_horse_id_captured_at_key"), "horse_profile_history", type_="unique")
    op.drop_index(op.f("idx_horse_profile_history_horse_captured"), table_name="horse_profile_history")
    op.create_index(
        "idx_horse_profile_history_horse_captured", "horse_profile_history", ["horse_id", "captured_at"], unique=False
    )
    op.create_unique_constraint(
        "uq_horse_profile_history_horse_captured", "horse_profile_history", ["horse_id", "captured_at"]
    )
    op.drop_constraint(op.f("horse_sectional_runner_id_section_no_key"), "horse_sectional", type_="unique")
    op.create_unique_constraint("uq_horse_sectional_runner_section", "horse_sectional", ["runner_id", "section_no"])
    op.drop_constraint(op.f("meeting_date_venue_code_key"), "meeting", type_="unique")
    op.create_unique_constraint("uq_meeting_date_venue", "meeting", ["date", "venue_code"])
    op.drop_constraint(op.f("race_meeting_id_race_no_key"), "race", type_="unique")
    op.create_unique_constraint("uq_race_meeting_raceno", "race", ["meeting_id", "race_no"])
    op.drop_constraint(op.f("runner_race_id_horse_id_key"), "runner", type_="unique")
    op.create_unique_constraint("uq_runner_race_horse", "runner", ["race_id", "horse_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_runner_race_horse", "runner", type_="unique")
    op.create_unique_constraint(
        op.f("runner_race_id_horse_id_key"), "runner", ["race_id", "horse_id"], postgresql_nulls_not_distinct=False
    )
    op.drop_constraint("uq_race_meeting_raceno", "race", type_="unique")
    op.create_unique_constraint(
        op.f("race_meeting_id_race_no_key"), "race", ["meeting_id", "race_no"], postgresql_nulls_not_distinct=False
    )
    op.drop_constraint("uq_meeting_date_venue", "meeting", type_="unique")
    op.create_unique_constraint(
        op.f("meeting_date_venue_code_key"), "meeting", ["date", "venue_code"], postgresql_nulls_not_distinct=False
    )
    op.drop_constraint("uq_horse_sectional_runner_section", "horse_sectional", type_="unique")
    op.create_unique_constraint(
        op.f("horse_sectional_runner_id_section_no_key"),
        "horse_sectional",
        ["runner_id", "section_no"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint("uq_horse_profile_history_horse_captured", "horse_profile_history", type_="unique")
    op.drop_index("idx_horse_profile_history_horse_captured", table_name="horse_profile_history")
    op.create_index(
        op.f("idx_horse_profile_history_horse_captured"),
        "horse_profile_history",
        ["horse_id", sa.literal_column("captured_at DESC")],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("horse_profile_history_horse_id_captured_at_key"),
        "horse_profile_history",
        ["horse_id", "captured_at"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "horse_profile_history",
        "captured_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    # ### end Alembic commands ###
