"""make_horse_code_name_unique

Revision ID: a650ac14fa0b
Revises: d2a6620d97e6
Create Date: 2026-01-09 02:14:27.629463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a650ac14fa0b'
down_revision: Union[str, Sequence[str], None] = 'd2a6620d97e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('horse_code_key'), 'horse', type_='unique')
    op.create_unique_constraint('uq_horse_code_name', 'horse', ['code', 'name_cn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_horse_code_name', 'horse', type_='unique')
    op.create_unique_constraint(op.f('horse_code_key'), 'horse', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
