"""initial_schema_merged_horse_tables

Revision ID: d2a6620d97e6
Revises: 
Create Date: 2026-01-09 02:09:11.067649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2a6620d97e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_horse_profile_history_horse_captured'), table_name='horse_profile_history')
    op.drop_table('horse_profile_history')
    op.alter_column('horse', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('horse_id_seq'::regclass)"))
    op.alter_column('horse_sectional', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('horse_sectional', 'race_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('horse_sectional', 'runner_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('horse_sectional', 'horse_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('horse_sectional_runner_id_section_no_key'), 'horse_sectional', type_='unique')
    op.create_unique_constraint('uq_horse_sectional_runner_section', 'horse_sectional', ['runner_id', 'section_no'])
    op.alter_column('jockey', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('jockey_id_seq'::regclass)"))
    op.alter_column('jockey', 'code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('jockey', 'name_cn',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_unique_constraint(None, 'jockey', ['name_cn'])
    op.alter_column('meeting', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('meeting_id_seq'::regclass)"))
    op.drop_constraint(op.f('meeting_date_venue_code_key'), 'meeting', type_='unique')
    op.create_unique_constraint('uq_meeting_date_venue', 'meeting', ['date', 'venue_code'])
    op.alter_column('race', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('race_id_seq'::regclass)"))
    op.alter_column('race', 'meeting_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('race_meeting_id_race_no_key'), 'race', type_='unique')
    op.create_unique_constraint('uq_race_meeting_raceno', 'race', ['meeting_id', 'race_no'])
    op.alter_column('runner', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('runner_id_seq'::regclass)"))
    op.alter_column('runner', 'race_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('runner', 'horse_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('runner', 'jockey_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('runner', 'trainer_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(op.f('runner_race_id_horse_id_key'), 'runner', type_='unique')
    op.create_unique_constraint('uq_runner_race_horse', 'runner', ['race_id', 'horse_id'])
    op.alter_column('trainer', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('trainer_id_seq'::regclass)"))
    op.alter_column('trainer', 'code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('trainer', 'name_cn',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_unique_constraint(None, 'trainer', ['name_cn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainer', type_='unique')
    op.alter_column('trainer', 'name_cn',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('trainer', 'code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('trainer', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('trainer_id_seq'::regclass)"))
    op.drop_constraint('uq_runner_race_horse', 'runner', type_='unique')
    op.create_unique_constraint(op.f('runner_race_id_horse_id_key'), 'runner', ['race_id', 'horse_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('runner', 'trainer_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('runner', 'jockey_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('runner', 'horse_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('runner', 'race_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('runner', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('runner_id_seq'::regclass)"))
    op.drop_constraint('uq_race_meeting_raceno', 'race', type_='unique')
    op.create_unique_constraint(op.f('race_meeting_id_race_no_key'), 'race', ['meeting_id', 'race_no'], postgresql_nulls_not_distinct=False)
    op.alter_column('race', 'meeting_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('race', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('race_id_seq'::regclass)"))
    op.drop_constraint('uq_meeting_date_venue', 'meeting', type_='unique')
    op.create_unique_constraint(op.f('meeting_date_venue_code_key'), 'meeting', ['date', 'venue_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('meeting', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('meeting_id_seq'::regclass)"))
    op.drop_constraint(None, 'jockey', type_='unique')
    op.alter_column('jockey', 'name_cn',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('jockey', 'code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('jockey', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('jockey_id_seq'::regclass)"))
    op.drop_constraint('uq_horse_sectional_runner_section', 'horse_sectional', type_='unique')
    op.create_unique_constraint(op.f('horse_sectional_runner_id_section_no_key'), 'horse_sectional', ['runner_id', 'section_no'], postgresql_nulls_not_distinct=False)
    op.alter_column('horse_sectional', 'horse_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('horse_sectional', 'runner_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('horse_sectional', 'race_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('horse_sectional', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('horse', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('horse_id_seq'::regclass)"))
    op.create_table('horse_profile_history',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('horse_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('captured_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('origin', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('colour', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('import_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('season_prize_hkd', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lifetime_prize_hkd', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('record_wins', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('record_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('record_thirds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('record_starts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last10_starts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_location', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('current_location_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('import_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('owner_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('current_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('season_start_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sire_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('dam_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('dam_sire_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horse.id'], name=op.f('horse_profile_history_horse_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('horse_profile_history_pkey')),
    sa.UniqueConstraint('horse_id', 'captured_at', name=op.f('horse_profile_history_horse_id_captured_at_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_horse_profile_history_horse_captured'), 'horse_profile_history', ['horse_id', sa.literal_column('captured_at DESC')], unique=False)
    # ### end Alembic commands ###
